version: '3.7'
services:

  v2ray:
    container_name: proxy-v2ray
    image: v2fly/v2fly-core
    restart: always
    volumes: 
      - ./v2ray:/etc/v2ray
    ports: 
      - 127.0.0.1:10808:10808
    networks:
      - app_net

  nginx:
    container_name: proxy-nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
    ports:
      - 127.0.0.1:10809:80
    networks: 
      - app_net

networks:
  app_net:
    ipam:
      driver: default
